### ISSUE TITLE
WIT data not found

### ISSUE THREAD

**Issue by MaxyLee** [JerryYLi/valhalla-nmt#1]
I cannot find the download link of the WIT data on your [project page](http://svcl.ucsd.edu/projects/valhalla/). Could you please the download link or preprocess code of WIT? Thanks!

**Comment by devaansh100** [comment]
Would like to follow up on this. Thank you!

**Comment by JerryYLi** [comment]
Apologies for the late response. The processed WIT data is now available on [Releases](https://github.com/JerryYLi/valhalla-nmt/releases) page.
